refresh-project/refresh-project/Controllers/FormulirController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using refresh_project.Models;
using refresh_project.Models.View;
using System.Text.RegularExpressions;


namespace refresh_project.Controllers
{
    public class FormulirController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            return PartialView(FormulirModelAccess.GetListAll());
        }

        public ActionResult Create()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult Create(FormulirModelView paramModel)
        {
            try
            {
                paramModel.is_delete = false;

                FormulirModelAccess.Message = string.Empty;
                if (null == paramModel.name|| null == paramModel.e_mail|| null == paramModel.npm_nis|| null == paramModel.age|| null == paramModel.gender|| null == paramModel.telp|| null == paramModel.address|| null == paramModel.address_asal|| null == paramModel.domisili)
                {
                    FormulirModelAccess.Message += "Anda belum memasukan semua data. Silahkan ulang kembali";
                }
                if (string.IsNullOrEmpty(FormulirModelAccess.Message))
                {
                    return Json(new
                    {
                        success = FormulirModelAccess.Insert(paramModel),
                        message = FormulirModelAccess.Message
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = FormulirModelAccess.Message },
                    JsonRequestBehavior.AllowGet);
                    //return View();
                }
            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }




        public ActionResult Detail(Int32 paramId)
        {
            return PartialView(FormulirModelAccess.GetDetailById(paramId));
        }



        public ActionResult Edit(Int32 paramId)
        {
            return PartialView(FormulirModelAccess.GetDetailById(paramId));
        }

        [HttpPost]
        public ActionResult Edit(FormulirModelView paramModel)
        {
            try
            {
                FormulirModelAccess.Message = string.Empty;

                if (null == paramModel.name || null == paramModel.e_mail || null == paramModel.npm_nis || 0 == paramModel.age || null == paramModel.telp || null == paramModel.address || null == paramModel.address_asal || null == paramModel.domisili)
                {
                    FormulirModelAccess.Message += "Anda belum memasukan semua data. Silahkan ulang kembali";
                }
                if (string.IsNullOrEmpty(FormulirModelAccess.Message))
                {
                    return Json(new
                    {
                        success = FormulirModelAccess.Update(paramModel),
                        message = FormulirModelAccess.Message
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = FormulirModelAccess.Message },
                    JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new
                {
                    success = false,
                    message = hasError.Message
                },
                JsonRequestBehavior.AllowGet);
            }
        }


        public ActionResult Delete(Int32 Id)
        {
            return PartialView(FormulirModelAccess.GetDetailById(Id));
        }

        [HttpPost]
        public ActionResult Delete(FormulirModelView paramModel)
        {
            try
            {
                return Json(new
                {
                    success = FormulirModelAccess.Delete(paramModel),
                    message = FormulirModelAccess.Message
                }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception hasError)
            {
                return Json(new
                {
                    success = false,
                    message = hasError.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

refresh-project/refresh-project/Views/Formulir/Create.cshtml
@model refresh_project.Models.View.FormulirModelView


@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<form style="color:#de0000">
    <div>
        <div class="row" style="padding-top:30px">
            <div class="col-lg-6" style="margin:auto">
                <label>Email</label>
                @Html.EditorFor(model => model.e_mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.e_mail, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row" style="padding-top:30px">
            <div class="col-lg-6" style="margin:auto">
                <label>Nama</label>
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row" style="padding-top:30px">
            <div class="col-lg-6" style="margin:auto">
                <label>NPM/NIS</label>
                @Html.EditorFor(model => model.npm_nis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.npm_nis, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row" style="padding-top:30px">
            <div class="col-lg-6" style="margin:auto">
                <label>Umur</label>
                @Html.EditorFor(model => model.age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.age, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row" style="padding-top:30px">
            <div class="col-lg-6" style="margin:auto">
                <label>Jenis Kelamin</label>
                <br />
                <input type="radio" id="pria" name="gender" value=true>
                <label for="male">Laki-laki</label><br>
                <input type="radio" id="wanita" name="gender" value=false>
                <label for="male">Perempuan</label><br>
                @*@Html.EditorFor(model => model.gender)
                @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })*@
            </div>
        </div>
        <div class="row" style="padding-top:30px">
            <div class="col-lg-6" style="margin:auto">
                <label>Telp</label>
                @Html.EditorFor(model => model.telp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telp, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row" style="padding-top:30px">
            <div class="col-lg-6" style="margin:auto">
                <label>Alamat Saat Ini</label>
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row" style="padding-top:30px">
            <div class="col-lg-6" style="margin:auto">
                <label>Alamat Asal</label>
                @Html.EditorFor(model => model.address_asal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address_asal, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row" style="padding-top:30px">
            <div class="col-lg-6" style="margin:auto">
                <label>Saat Ini Saya Berada Di:</label>
                @Html.EditorFor(model => model.domisili, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.domisili, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="row" style="padding-top:15px">
            <div class="col-lg-12">
                <input type="submit" value="Save" class="btn btn-default col-md-offset-7" id="btn_add_save" style="background-color:#1181d1; color:white; float:right" />
            </div>
        </div>


    </div>
</form>
















@*<h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>FormulirModelView</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.is_delete, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.is_delete)
                        @Html.ValidationMessageFor(model => model.is_delete, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.e_mail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.e_mail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.e_mail, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.npm_nis, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.npm_nis, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.npm_nis, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.age, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.age, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.gender)
                        @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.telp, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.telp, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.telp, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.address_asal, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.address_asal, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.address_asal, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.domisili, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.domisili, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.domisili, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

refresh-project/refresh-project/Views/Formulir/Delete.cshtml
@model refresh_project.Models.View.FormulirModelView

@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-md-3"><i class="fas fa-trash" style="display:block; width: 70%; height: 70%; margin: auto; color:darkred;  padding-top:15px"></i></div>
    <div class="form-group col-md-9" style="padding-top:20px; color:darkred">
        <div>
            <h4 style="margin: auto">Anda yakin ingin menghapus data </h4>
            <h4 style="margin: auto">@Html.DisplayFor(model => model.name) ?</h4>
            @Html.HiddenFor(model => Model.id)
        </div>
    </div>
</div>
<div class="row" style="padding-top:40px">
    <div class="col-md-12">
        <div class="btn-group  col-md-offset-5" role="group" aria-label="Basic example" style="float:right">
            <button type="button" class="btn" style="background-color:orangered; color:white; width:90px" id="cancel" data-dismiss="modal">Tidak</button>
            <button type="button" class="btn" style="background-color:darkred; color:white; width:90px" id="btn_delete_save">Iya</button>
        </div>
    </div>
</div>








@*<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FormulirModelView</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.is_delete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.is_delete)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.e_mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.e_mail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.npm_nis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.npm_nis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address_asal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address_asal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.domisili)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.domisili)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>*@

refresh-project/refresh-project/Views/Formulir/Detail.cshtml
@model refresh_project.Models.View.FormulirModelView


<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.e_mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.e_mail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.npm_nis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.npm_nis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address_asal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address_asal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.domisili)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.domisili)
        </dd>

    </dl>
</div>
@*<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

refresh-project/refresh-project/Views/Formulir/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="modal fade" id="modal-form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabelAdd" aria-hidden="true">
    <div class="modal-dialog" role="document" style="width:920px; max-width:100%">
        <!-- modal content -->
        <div class="modal-content" style=" border-color:#343a40">
            <!-- modal header -->
            <div class="modal-header" id="modal-header" style="background-color:#343a40">
                <h3 class="modal-title" id="modal-title-popup"
                    style="color:white">
                    Judul Modal
                </h3>

                <button class="close" style="color:white" id="tutup" data-dismiss="modal">
                    &times;
                </button>
            </div>
            <!-- modal body dan footer -->
            <div class="div-bind-form" id="div-bind-form" style="margin-top: 5px; margin-left: 20px; margin-right: 20px; margin-bottom: 15px">
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>
</div>



<!-- modal popup bootstrap - Delete Form -->
<div class="modal fade" id="modal-form-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabelAdd" aria-hidden="true">
    <div class="modal-dialog" role="document" style="width:500px">
        <!-- modal content -->
        <div class="modal-content" style=" border-color:darkred">
            <!-- modal header -->
            <div class="modal-header" id="modal-header" style="background-color:darkred">
                <h3 class="modal-title" id="modal-title-popup-delete"
                    style="color:white">
                    Judul Modal
                </h3>
                <button class="close" style="color:white" id="tutup-delete" data-dismiss="modal">
                    &times;
                </button>
            </div>
            <!-- modal body dan footer -->
            <div class="div-bind-form" id="div-bind-form" style="margin-top:10px; margin-left:10px; margin-right:10px; margin-bottom:10px">
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>
</div>


<div id="table-list" style="background-color:white">
    <div class="progress progress-striped active"
         style="margin-bottom:0">
        <div class="progress-bar" style="width:100%">
        </div>
    </div>
</div>

<script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            ShowList();
        });
        var vjs_loading = '<div class="progress progress-striped active" style="margin-bottom:0"> <div class="progress-bar" style="width:100%"> </div> </div>';

        function ShowList() {
            $("#table-list").html(vjs_loading);
            $.ajax({
                url: '@Url.Action("List", "Formulir")',
                type: 'get',
                success: function (result) {
                    $("#table-list").html(result);
                }
            });
        }



        //Popup Tambah Data
        $(document).on("click", "#btn_create", function () {
            $("#table-list").html(vjs_loading);
            $.ajax({
                url: '@Url.Action("Create", "Formulir")',
                type: 'get',
                success: function (result) {
                    $("#table-list").html(result);
                }
            });
        });

        $(document).on("click", "#btn_add_save", function () {
            var vjs_e_mail = $("#e_mail").val();
            var vjs_name = $("#name").val();
            var vjs_npm_nis = $("#npm_nis").val();
            var vjs_age = $("#age").val();
           
            if ($("#pria").is(":checked")) {
                var vjs_gender = $("#pria").val();
            }
             if ($("#wanita").is(":checked")) {
                var vjs_gender = $("#wanita").val();
            }
            var vjs_telp = $("#telp").val();
            var vjs_address = $("#address").val();
            var vjs_address_asal = $("#address_asal").val();
            var vjs_domisili = $("#domisili").val();


             var vjs_schedule_date = $("#schedule_date").val();
            vjs_schedule_date == "" ? $(".validasi1").show() : $(".validasi1").hide();



            var item = {
                e_mail: vjs_e_mail,
                name: vjs_name,
                npm_nis: vjs_npm_nis,
                age: vjs_age,
                gender: vjs_gender,
                telp: vjs_telp,
                address: vjs_address,
                address_asal: vjs_address_asal,
                domisili: vjs_domisili
            };
            $.ajax({
                url: '@Url.Action("Create", "Formulir")',
                type: 'post',
                data: { paramModel: item },
                success: function (result) {
                    if (result.success) {
                        alert("Data Berhasil Ditambah");
                        ShowList();
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });


        //Popup Detail
        $(document).on("click", "#detail-covid", function () {
            $("#modal-form").modal("show");
            $("#modal-title-popup").html("Detail");
            $(".div-bind-form").html(vjs_loading);

            var vjs_id = $(this).attr("data-id");

            $.ajax({
                url: '@Url.Action("Detail", "Formulir")',
                type: 'get',
                data: { paramId: vjs_id },
                success: function (result) {
                    $(".div-bind-form").html(result);
                }
            })
        });



        //Popup Edit
        $(document).on("click", "#edit-covid", function () {
            $("#modal-form").modal("show");
            $("#modal-title-popup").html("Edit");
            $(".div-bind-form").html(vjs_loading);

            var vjs_id = $(this).attr("data-id");

            $.ajax({
                url: '@Url.Action("Edit", "Formulir")',
                type: 'get',
                data: { paramId: vjs_id },
                success: function (result) {
                    $(".div-bind-form").html(result);
                }
            })
        });

        $(document).on("click", "#btn_edit_save", function () {
            var vjs_id = $("#id").val();
            var vjs_e_mail = $("#e_mail").val();
            var vjs_name = $("#name").val();
            var vjs_npm_nis = $("#npm_nis").val();
            var vjs_age = $("#age").val();
            var vjs_gender = $("#gender").val();
            var vjs_telp = $("#telp").val();
            var vjs_address = $("#address").val();
            var vjs_address_asal = $("#address_asal").val();
            var vjs_domisili = $("#domisili").val();


            var itemEdit = {
                id: vjs_id,
                e_mail: vjs_e_mail,
                name: vjs_name,
                npm_nis: vjs_npm_nis,
                age: vjs_age,
                gender: vjs_gender,
                telp: vjs_telp,
                address: vjs_address,
                address_asal: vjs_address_asal,
                domisili: vjs_domisili
            };

            $.ajax({
                url: '@Url.Action("Edit", "Formulir")',
                type: 'post',
                data: { paramModel: itemEdit },
                success: function (result) {
                    if (result.success) {
                        $("#modal-form").modal("hide");
                        alert("Data Berhasil Diubah");
                        ShowList();
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });



        //Popup Delete
        $(document).on("click", "#delete-covid", function () {
            $("#modal-form-delete").modal("show");
            $("#modal-title-popup-delete").html("Hapus Data ?");
            $(".div-bind-form").html(vjs_loading);

            var vjs_id = $(this).attr("data-id");

            $.ajax({
                url: '@Url.Action("Delete","Formulir")',
                type: 'get',
                data: { Id: vjs_id },
                success: function (result) {
                    $(".div-bind-form").html(result);
                }
            });
        });

        $(document).on("click", "#btn_delete_save", function () {
            var vjs_id = $("#id").val();

            var itemDelete = {
                id: vjs_id
            };
            $.ajax({
                url: '@Url.Action("Delete", "Formulir")',
                type: 'post',
                data: { paramModel: itemDelete },
                success: function (result) {
                    if (result.success) {
                        $("#modal-form-delete").modal("hide");
                        alert("Data Berhasil Dihapus");
                        ShowList();
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });





    </script>
}